### ISSUE TITLE
Build broken with go 1.18

### ISSUE THREAD

**Issue by jameshcorbett** [HewlettPackard/dws#14]
With go 1.18, the `make controller-gen` target fails to create a `bin/` directory and to create `bin/controller-gen`. All of the targets that depend on `make controller-gen` (e.g. `make docker-build`) therefore fail as well.

I was able to resolve the issue by downgrading to `1.17`.

**Comment by roehrich-hpe** [comment]
Closed by [PR35](https://github.com/HewlettPackard/dws/pull/35)
